-- Add TASK_DELEGATION_ENABLED preference type
ALTER TABLE member_preferences
MODIFY COLUMN question_type ENUM('ROOM_PREFERENCE', 'MACHINE_PREFERENCE', 'SKILL_LEVEL', 'TASK_DELEGATION_ENABLED') NOT NULL;
