
# THIS FILE IS AUTOMATICALLY GENERATED BY THE build_locales.py SCRIPT. DO NOT EDIT.

from typing import Any, Callable, Literal, Protocol, overload

from service import logging

from .en import LOCALE as en
from .sv import LOCALE as sv

RESOURCES = {
    "en": en,
    "sv": sv
}

logger = logging.getLogger("i18n")

class box_terminatorTranslator(Protocol):
    @overload
    def __call__(self, key: Literal["can_terminate","enter_label_id","message_templates.memberbooth_box_cleaned_away","message_templates.memberbooth_box_cleaned_away_sms","message_templates.memberbooth_box_expired","message_templates.memberbooth_box_expiring_soon","message_templates.memberbooth_label_cleaned_away","message_templates.memberbooth_label_cleaned_away_sms","message_templates.memberbooth_label_expired","message_templates.memberbooth_label_expiring_soon","message_templates.memberbooth_label_report","message_templates.memberbooth_label_report_sms","no_matching_labels","view_label","will_send","box_terminator:can_terminate","box_terminator:enter_label_id","box_terminator:message_templates.memberbooth_box_cleaned_away","box_terminator:message_templates.memberbooth_box_cleaned_away_sms","box_terminator:message_templates.memberbooth_box_expired","box_terminator:message_templates.memberbooth_box_expiring_soon","box_terminator:message_templates.memberbooth_label_cleaned_away","box_terminator:message_templates.memberbooth_label_cleaned_away_sms","box_terminator:message_templates.memberbooth_label_expired","box_terminator:message_templates.memberbooth_label_expiring_soon","box_terminator:message_templates.memberbooth_label_report","box_terminator:message_templates.memberbooth_label_report_sms","box_terminator:no_matching_labels","box_terminator:view_label","box_terminator:will_send"]) -> str: ...

    @overload
    def __call__(self, key: Literal["can_be_terminated_in","expires_future","expires_past","box_terminator:can_be_terminated_in","box_terminator:expires_future","box_terminator:expires_past"], *, relative_time: str | int | float) -> str: ...

def __call__(self, key: str, **kwargs: Any) -> str: ...


class brandTranslator(Protocol):
    def __call__(self, key: Literal["billing_address","email","homepage_url","makerspace_name","organization_number","brand:billing_address","brand:email","brand:homepage_url","brand:makerspace_name","brand:organization_number"]) -> str: ...

class commonTranslator(Protocol):
    def __call__(self, key: Literal["todo","common:todo"]) -> str: ...

class member_quizzesTranslator(Protocol):
    def __call__(self, key: Literal["error_loading","loading","no_quizzes","table.completion","table.correctly_answered","table.quiz","member_quizzes:error_loading","member_quizzes:loading","member_quizzes:no_quizzes","member_quizzes:table.completion","member_quizzes:table.correctly_answered","member_quizzes:table.quiz"]) -> str: ...

class member_tasksTranslator(Protocol):
    @overload
    def __call__(self, key: Literal["actions.already_completed_by_someone_else","actions.assigned","actions.completed","actions.ignored","actions.not_done_confused","actions.not_done_did_something_else","actions.not_done_forgot","actions.not_done_no_time","actions.not_done_rerolled","by_label.count","by_label.label","by_label.no_labels","by_label.title","error_loading","history.date","history.labels","history.no_tasks","history.status","history.task","history.title","loading","no_data","summary.not_specified","summary.preferred_rooms","summary.skill_level","summary.time_at_space","summary.title","summary.total_completed","member_tasks:actions.already_completed_by_someone_else","member_tasks:actions.assigned","member_tasks:actions.completed","member_tasks:actions.ignored","member_tasks:actions.not_done_confused","member_tasks:actions.not_done_did_something_else","member_tasks:actions.not_done_forgot","member_tasks:actions.not_done_no_time","member_tasks:actions.not_done_rerolled","member_tasks:by_label.count","member_tasks:by_label.label","member_tasks:by_label.no_labels","member_tasks:by_label.title","member_tasks:error_loading","member_tasks:history.date","member_tasks:history.labels","member_tasks:history.no_tasks","member_tasks:history.status","member_tasks:history.task","member_tasks:history.title","member_tasks:loading","member_tasks:no_data","member_tasks:summary.not_specified","member_tasks:summary.preferred_rooms","member_tasks:summary.skill_level","member_tasks:summary.time_at_space","member_tasks:summary.title","member_tasks:summary.total_completed"]) -> str: ...

    @overload
    def __call__(self, key: Literal["actions.not_done","member_tasks:actions.not_done"], *, count: int) -> str: ...

def __call__(self, key: str, **kwargs: Any) -> str: ...


class timeTranslator(Protocol):
    @overload
    def __call__(self, key: Literal["relative_generic.now","time:relative_generic.now"]) -> str: ...

    @overload
    def __call__(self, key: Literal["duration.days","duration.hours","duration.minutes","relative_generic.days_ago","relative_generic.hours_ago","relative_generic.in_days","relative_generic.in_hours","relative_generic.in_minutes","relative_generic.minutes_ago","time:duration.days","time:duration.hours","time:duration.minutes","time:relative_generic.days_ago","time:relative_generic.hours_ago","time:relative_generic.in_days","time:relative_generic.in_hours","time:relative_generic.in_minutes","time:relative_generic.minutes_ago"], *, count: int) -> str: ...

    @overload
    def __call__(self, key: Literal["relative_generic.date_future","relative_generic.date_past","time:relative_generic.date_future","time:relative_generic.date_past"], *, date: str | int | float) -> str: ...

def __call__(self, key: str, **kwargs: Any) -> str: ...

@overload
def translate(key: Literal["can_terminate","enter_label_id","message_templates.memberbooth_box_cleaned_away","message_templates.memberbooth_box_cleaned_away_sms","message_templates.memberbooth_box_expired","message_templates.memberbooth_box_expiring_soon","message_templates.memberbooth_label_cleaned_away","message_templates.memberbooth_label_cleaned_away_sms","message_templates.memberbooth_label_expired","message_templates.memberbooth_label_expiring_soon","message_templates.memberbooth_label_report","message_templates.memberbooth_label_report_sms","no_matching_labels","view_label","will_send","box_terminator:can_terminate","box_terminator:enter_label_id","box_terminator:message_templates.memberbooth_box_cleaned_away","box_terminator:message_templates.memberbooth_box_cleaned_away_sms","box_terminator:message_templates.memberbooth_box_expired","box_terminator:message_templates.memberbooth_box_expiring_soon","box_terminator:message_templates.memberbooth_label_cleaned_away","box_terminator:message_templates.memberbooth_label_cleaned_away_sms","box_terminator:message_templates.memberbooth_label_expired","box_terminator:message_templates.memberbooth_label_expiring_soon","box_terminator:message_templates.memberbooth_label_report","box_terminator:message_templates.memberbooth_label_report_sms","box_terminator:no_matching_labels","box_terminator:view_label","box_terminator:will_send"]) -> str: ...


@overload
def translate(key: Literal["can_be_terminated_in","expires_future","expires_past","box_terminator:can_be_terminated_in","box_terminator:expires_future","box_terminator:expires_past"], *, relative_time: str | int | float) -> str: ...


@overload
def translate(key: Literal["billing_address","email","homepage_url","makerspace_name","organization_number","brand:billing_address","brand:email","brand:homepage_url","brand:makerspace_name","brand:organization_number"]) -> str: ...


@overload
def translate(key: Literal["todo","common:todo"]) -> str: ...


@overload
def translate(key: Literal["error_loading","loading","no_quizzes","table.completion","table.correctly_answered","table.quiz","member_quizzes:error_loading","member_quizzes:loading","member_quizzes:no_quizzes","member_quizzes:table.completion","member_quizzes:table.correctly_answered","member_quizzes:table.quiz"]) -> str: ...


@overload
def translate(key: Literal["actions.already_completed_by_someone_else","actions.assigned","actions.completed","actions.ignored","actions.not_done_confused","actions.not_done_did_something_else","actions.not_done_forgot","actions.not_done_no_time","actions.not_done_rerolled","by_label.count","by_label.label","by_label.no_labels","by_label.title","error_loading","history.date","history.labels","history.no_tasks","history.status","history.task","history.title","loading","no_data","summary.not_specified","summary.preferred_rooms","summary.skill_level","summary.time_at_space","summary.title","summary.total_completed","member_tasks:actions.already_completed_by_someone_else","member_tasks:actions.assigned","member_tasks:actions.completed","member_tasks:actions.ignored","member_tasks:actions.not_done_confused","member_tasks:actions.not_done_did_something_else","member_tasks:actions.not_done_forgot","member_tasks:actions.not_done_no_time","member_tasks:actions.not_done_rerolled","member_tasks:by_label.count","member_tasks:by_label.label","member_tasks:by_label.no_labels","member_tasks:by_label.title","member_tasks:error_loading","member_tasks:history.date","member_tasks:history.labels","member_tasks:history.no_tasks","member_tasks:history.status","member_tasks:history.task","member_tasks:history.title","member_tasks:loading","member_tasks:no_data","member_tasks:summary.not_specified","member_tasks:summary.preferred_rooms","member_tasks:summary.skill_level","member_tasks:summary.time_at_space","member_tasks:summary.title","member_tasks:summary.total_completed"]) -> str: ...


@overload
def translate(key: Literal["actions.not_done","member_tasks:actions.not_done"], *, count: int) -> str: ...


@overload
def translate(key: Literal["relative_generic.now","time:relative_generic.now"]) -> str: ...


@overload
def translate(key: Literal["duration.days","duration.hours","duration.minutes","relative_generic.days_ago","relative_generic.hours_ago","relative_generic.in_days","relative_generic.in_hours","relative_generic.in_minutes","relative_generic.minutes_ago","time:duration.days","time:duration.hours","time:duration.minutes","time:relative_generic.days_ago","time:relative_generic.hours_ago","time:relative_generic.in_days","time:relative_generic.in_hours","time:relative_generic.in_minutes","time:relative_generic.minutes_ago"], *, count: int) -> str: ...


@overload
def translate(key: Literal["relative_generic.date_future","relative_generic.date_past","time:relative_generic.date_future","time:relative_generic.date_past"], *, date: str | int | float) -> str: ...

def translate(key: str, *, count: int | None = None, language: Literal["en", "sv"]="en", **kwargs: Any) -> str | list[str]:
    if count is not None:
        specific_key = f"{key}_{'zero' if count == 0 else 'one' if count == 1 else 'two' if count == 2 else 'many'}"
        v: str = RESOURCES[language].get(specific_key)
        if v is None and count > 2:
            v = RESOURCES[language].get(f"{key}_many")
        if v is None:
            v = RESOURCES[language].get(f"{key}_other")
    else:
        v = RESOURCES[language].get(key)

    if v is None:
        logger.error(f"Missing translation for key: {key}")
        return key

    if kwargs:
        return v.format(count=count, **kwargs)
    return v

@overload
def translator(prefix: Literal['box_terminator']) -> box_terminatorTranslator: ...


@overload
def translator(prefix: Literal['brand']) -> brandTranslator: ...


@overload
def translator(prefix: Literal['common']) -> commonTranslator: ...


@overload
def translator(prefix: Literal['member_quizzes']) -> member_quizzesTranslator: ...


@overload
def translator(prefix: Literal['member_tasks']) -> member_tasksTranslator: ...


@overload
def translator(prefix: Literal['time']) -> timeTranslator: ...



def translator(prefix: str) -> Callable[..., str | list[str]]:
    def translate(key: str, **kwargs: Any) -> str | list[str]:
        return f"{prefix}:{key}"

    return translate

