// THIS FILE IS AUTOMATICALLY GENERATED BY THE build_locales.py SCRIPT. DO NOT EDIT.
        // This is necessary because while i18next supports typescript, it is very brittle and it has a tendency
        // to cause the typescript compiler to error out because it encountered a recursion limit in its type inference.
        // Pre-compiling the types like this allows us to avoid that issue, for the price of having a build step.

        import en from "./generated_locales/en.json";
import sv from "./generated_locales/sv.json";

        export const LOCALE_RESOURCES = {
            en,
    sv,

        } as const;

        export type LOCALE_SCHEMA = {
        	"box_terminator":
((key: "can_terminate" | "enter_label_id" | "message_templates.memberbooth_box_cleaned_away" | "message_templates.memberbooth_box_cleaned_away_sms" | "message_templates.memberbooth_box_expired" | "message_templates.memberbooth_box_expiring_soon" | "message_templates.memberbooth_label_cleaned_away" | "message_templates.memberbooth_label_cleaned_away_sms" | "message_templates.memberbooth_label_expired" | "message_templates.memberbooth_label_expiring_soon" | "message_templates.memberbooth_label_report" | "message_templates.memberbooth_label_report_sms" | "no_matching_labels" | "view_label" | "will_send") => string)
		& ((key: "can_be_terminated_in" | "expires_future" | "expires_past", args: { "relative_time": string | number}) => string)
	"brand":
((key: "billing_address" | "email" | "homepage_url" | "makerspace_name" | "organization_number") => string)
	"common":
((key: "todo") => string)
	"member_quizzes":
((key: "error_loading" | "loading" | "no_quizzes" | "table.completion" | "table.correctly_answered" | "table.quiz") => string)
	"member_tasks":
((key: "by_label.count" | "by_label.label" | "by_label.no_labels" | "by_label.title" | "error_loading" | "history.date" | "history.labels" | "history.no_tasks" | "history.status" | "history.task" | "history.title" | "loading" | "no_data" | "summary.not_specified" | "summary.preferred_rooms" | "summary.skill_level" | "summary.time_at_space" | "summary.title" | "summary.total_completed") => string)
	"task_statistics":
((key: "cards.completed_count" | "cards.last_completed" | "cards.last_completer" | "cards.never" | "cards.no_cards" | "cards.overdue" | "cards.score" | "cards.task" | "cards.title" | "error_loading" | "loading" | "member_preferences.count" | "member_preferences.description" | "member_preferences.no_data" | "member_preferences.no_responses" | "member_preferences.option" | "member_preferences.percentage" | "member_preferences.title" | "task_log.date" | "task_log.member" | "task_log.no_logs" | "task_log.room" | "task_log.show_only_completed" | "task_log.status" | "task_log.task" | "task_log.title" | "title") => string)
		& ((key: "member_preferences.total_respondents", args: { "count": string | number}) => string)
	"tasks":
((key: "actions.already_completed_by_someone_else" | "actions.assigned" | "actions.completed" | "actions.ignored" | "actions.not_done_confused" | "actions.not_done_did_something_else" | "actions.not_done_forgot" | "actions.not_done_no_time" | "actions.not_done_rerolled") => string)
		& ((key: "actions.not_done", args: { "count": string | number}) => string)
	"time":
((key: "relative_generic.now") => string)
		& ((key: "duration.days" | "duration.hours" | "duration.minutes" | "relative_generic.days_ago" | "relative_generic.hours_ago" | "relative_generic.in_days" | "relative_generic.in_hours" | "relative_generic.in_minutes" | "relative_generic.minutes_ago", args: { "count": string | number}) => string)
		& ((key: "relative_generic.date_future" | "relative_generic.date_past", args: { "date": string | number}) => string)
};

export type LOCALE_SCHEMA_GLOBAL = (
((key: "box_terminator:can_terminate" | "box_terminator:enter_label_id" | "box_terminator:message_templates.memberbooth_box_cleaned_away" | "box_terminator:message_templates.memberbooth_box_cleaned_away_sms" | "box_terminator:message_templates.memberbooth_box_expired" | "box_terminator:message_templates.memberbooth_box_expiring_soon" | "box_terminator:message_templates.memberbooth_label_cleaned_away" | "box_terminator:message_templates.memberbooth_label_cleaned_away_sms" | "box_terminator:message_templates.memberbooth_label_expired" | "box_terminator:message_templates.memberbooth_label_expiring_soon" | "box_terminator:message_templates.memberbooth_label_report" | "box_terminator:message_templates.memberbooth_label_report_sms" | "box_terminator:no_matching_labels" | "box_terminator:view_label" | "box_terminator:will_send") => string)
		& ((key: "box_terminator:can_be_terminated_in" | "box_terminator:expires_future" | "box_terminator:expires_past", args: { "relative_time": string | number}) => string)
		& ((key: "brand:billing_address" | "brand:email" | "brand:homepage_url" | "brand:makerspace_name" | "brand:organization_number") => string)
		& ((key: "common:todo") => string)
		& ((key: "member_quizzes:error_loading" | "member_quizzes:loading" | "member_quizzes:no_quizzes" | "member_quizzes:table.completion" | "member_quizzes:table.correctly_answered" | "member_quizzes:table.quiz") => string)
		& ((key: "member_tasks:by_label.count" | "member_tasks:by_label.label" | "member_tasks:by_label.no_labels" | "member_tasks:by_label.title" | "member_tasks:error_loading" | "member_tasks:history.date" | "member_tasks:history.labels" | "member_tasks:history.no_tasks" | "member_tasks:history.status" | "member_tasks:history.task" | "member_tasks:history.title" | "member_tasks:loading" | "member_tasks:no_data" | "member_tasks:summary.not_specified" | "member_tasks:summary.preferred_rooms" | "member_tasks:summary.skill_level" | "member_tasks:summary.time_at_space" | "member_tasks:summary.title" | "member_tasks:summary.total_completed") => string)
		& ((key: "task_statistics:cards.completed_count" | "task_statistics:cards.last_completed" | "task_statistics:cards.last_completer" | "task_statistics:cards.never" | "task_statistics:cards.no_cards" | "task_statistics:cards.overdue" | "task_statistics:cards.score" | "task_statistics:cards.task" | "task_statistics:cards.title" | "task_statistics:error_loading" | "task_statistics:loading" | "task_statistics:member_preferences.count" | "task_statistics:member_preferences.description" | "task_statistics:member_preferences.no_data" | "task_statistics:member_preferences.no_responses" | "task_statistics:member_preferences.option" | "task_statistics:member_preferences.percentage" | "task_statistics:member_preferences.title" | "task_statistics:task_log.date" | "task_statistics:task_log.member" | "task_statistics:task_log.no_logs" | "task_statistics:task_log.room" | "task_statistics:task_log.show_only_completed" | "task_statistics:task_log.status" | "task_statistics:task_log.task" | "task_statistics:task_log.title" | "task_statistics:title") => string)
		& ((key: "task_statistics:member_preferences.total_respondents", args: { "count": string | number}) => string)
		& ((key: "tasks:actions.already_completed_by_someone_else" | "tasks:actions.assigned" | "tasks:actions.completed" | "tasks:actions.ignored" | "tasks:actions.not_done_confused" | "tasks:actions.not_done_did_something_else" | "tasks:actions.not_done_forgot" | "tasks:actions.not_done_no_time" | "tasks:actions.not_done_rerolled") => string)
		& ((key: "tasks:actions.not_done", args: { "count": string | number}) => string)
		& ((key: "time:relative_generic.now") => string)
		& ((key: "time:duration.days" | "time:duration.hours" | "time:duration.minutes" | "time:relative_generic.days_ago" | "time:relative_generic.hours_ago" | "time:relative_generic.in_days" | "time:relative_generic.in_hours" | "time:relative_generic.in_minutes" | "time:relative_generic.minutes_ago", args: { "count": string | number}) => string)
		& ((key: "time:relative_generic.date_future" | "time:relative_generic.date_past", args: { "date": string | number}) => string)
);
