// THIS FILE IS AUTOMATICALLY GENERATED BY THE build_locales.py SCRIPT. DO NOT EDIT.
        // This is necessary because while i18next supports typescript, it is very brittle and it has a tendency
        // to cause the typescript compiler to error out because it encountered a recursion limit in its type inference.
        // Pre-compiling the types like this allows us to avoid that issue, for the price of having a build step.

        import en from "./generated_locales/en.json";
import sv from "./generated_locales/sv.json";

        export const LOCALE_RESOURCES = {
            en,
    sv,
    
        } as const;

        export type LOCALE_SCHEMA = {
        	"brand": 
((key: "billing_address" | "email" | "homepage_url" | "makerspace_name" | "organization_number") => string)
	"common": 
((key: "todo") => string)
	"time": 
((key: "relative_generic.now") => string) 
		& ((key: "relative_generic.days_ago" | "relative_generic.hours_ago" | "relative_generic.in_days" | "relative_generic.in_hours" | "relative_generic.in_minutes" | "relative_generic.minutes_ago", args: { "count": string | number}) => string) 
		& ((key: "relative_generic.date_future" | "relative_generic.date_past", args: { "date": string | number}) => string)
};

export type LOCALE_SCHEMA_GLOBAL = (
((key: "brand:billing_address" | "brand:email" | "brand:homepage_url" | "brand:makerspace_name" | "brand:organization_number") => string) 
		& ((key: "common:todo") => string) 
		& ((key: "time:relative_generic.now") => string) 
		& ((key: "time:relative_generic.days_ago" | "time:relative_generic.hours_ago" | "time:relative_generic.in_days" | "time:relative_generic.in_hours" | "time:relative_generic.in_minutes" | "time:relative_generic.minutes_ago", args: { "count": string | number}) => string) 
		& ((key: "time:relative_generic.date_future" | "time:relative_generic.date_past", args: { "date": string | number}) => string)
);
