// THIS FILE IS AUTOMATICALLY GENERATED BY THE build_locales.py SCRIPT. DO NOT EDIT.
        // This is necessary because while i18next supports typescript, it is very brittle and it has a tendency
        // to cause the typescript compiler to error out because it encountered a recursion limit in its type inference.
        // Pre-compiling the types like this allows us to avoid that issue, for the price of having a build step.

        import en from "./generated_locales/en.json";
import sv from "./generated_locales/sv.json";

        export const LOCALE_RESOURCES = {
            en,
    sv,

        } as const;

        export type LOCALE_SCHEMA = {
        	"box_terminator":
((key: "can_terminate" | "enter_label_id" | "message_templates.memberbooth_box_cleaned_away" | "message_templates.memberbooth_box_cleaned_away_sms" | "message_templates.memberbooth_box_expired" | "message_templates.memberbooth_box_expiring_soon" | "message_templates.memberbooth_label_cleaned_away" | "message_templates.memberbooth_label_cleaned_away_sms" | "message_templates.memberbooth_label_expired" | "message_templates.memberbooth_label_expiring_soon" | "message_templates.memberbooth_label_report" | "message_templates.memberbooth_label_report_sms" | "no_matching_labels" | "view_label" | "will_send") => string)
		& ((key: "can_be_terminated_in" | "expires_future" | "expires_past", args: { "relative_time": string | number}) => string)
	"brand":
((key: "billing_address" | "email" | "homepage_url" | "makerspace_name" | "organization_number") => string)
	"common":
((key: "todo") => string)
	"time":
((key: "relative_generic.now") => string)
		& ((key: "relative_generic.days_ago" | "relative_generic.hours_ago" | "relative_generic.in_days" | "relative_generic.in_hours" | "relative_generic.in_minutes" | "relative_generic.minutes_ago", args: { "count": string | number}) => string)
		& ((key: "relative_generic.date_future" | "relative_generic.date_past", args: { "date": string | number}) => string)
};

export type LOCALE_SCHEMA_GLOBAL = (
((key: "box_terminator:can_terminate" | "box_terminator:enter_label_id" | "box_terminator:message_templates.memberbooth_box_cleaned_away" | "box_terminator:message_templates.memberbooth_box_cleaned_away_sms" | "box_terminator:message_templates.memberbooth_box_expired" | "box_terminator:message_templates.memberbooth_box_expiring_soon" | "box_terminator:message_templates.memberbooth_label_cleaned_away" | "box_terminator:message_templates.memberbooth_label_cleaned_away_sms" | "box_terminator:message_templates.memberbooth_label_expired" | "box_terminator:message_templates.memberbooth_label_expiring_soon" | "box_terminator:message_templates.memberbooth_label_report" | "box_terminator:message_templates.memberbooth_label_report_sms" | "box_terminator:no_matching_labels" | "box_terminator:view_label" | "box_terminator:will_send") => string)
		& ((key: "box_terminator:can_be_terminated_in" | "box_terminator:expires_future" | "box_terminator:expires_past", args: { "relative_time": string | number}) => string)
		& ((key: "brand:billing_address" | "brand:email" | "brand:homepage_url" | "brand:makerspace_name" | "brand:organization_number") => string)
		& ((key: "common:todo") => string)
		& ((key: "time:relative_generic.now") => string)
		& ((key: "time:relative_generic.days_ago" | "time:relative_generic.hours_ago" | "time:relative_generic.in_days" | "time:relative_generic.in_hours" | "time:relative_generic.in_minutes" | "time:relative_generic.minutes_ago", args: { "count": string | number}) => string)
		& ((key: "time:relative_generic.date_future" | "time:relative_generic.date_past", args: { "date": string | number}) => string)
);
