-- MySQL Script generated by MySQL Workbench
-- Thu 27 Oct 2016 08:19:48 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema internal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entity` ;

CREATE TABLE IF NOT EXISTS `entity` (
  `entity_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `title` VARCHAR(80) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`entity_id`),
  INDEX `index2` (`type` ASC),
  INDEX `index3` (`deleted_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accounting_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounting_category` ;

CREATE TABLE IF NOT EXISTS `accounting_category` (
  `entity_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`entity_id`),
  CONSTRAINT `fk_accounting_category_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accounting_verification_series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounting_verification_series` ;

CREATE TABLE IF NOT EXISTS `accounting_verification_series` (
  `entity_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`entity_id`),
  CONSTRAINT `fk_accounting_verification_series_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accounting_period`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounting_period` ;

CREATE TABLE IF NOT EXISTS `accounting_period` (
  `entity_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  PRIMARY KEY (`entity_id`),
  CONSTRAINT `fk_accounting_period_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `entity` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accounting_instruction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounting_instruction` ;

CREATE TABLE IF NOT EXISTS `accounting_instruction` (
  `entity_id` INT(11) UNSIGNED NOT NULL,
  `instruction_number` INT(11) UNSIGNED NULL,
  `accounting_date` DATE NULL,
  `accounting_category` INT(11) UNSIGNED NULL,
  `importer` VARCHAR(45) NULL,
  `external_id` VARCHAR(255) NULL,
  `external_date` DATE NULL,
  `external_text` TEXT NULL,
  `external_data` TEXT NULL DEFAULT NULL,
  `accounting_verification_series` INT(11) UNSIGNED NULL,
  `accounting_period` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`entity_id`),
  INDEX `accounting_category` (`accounting_category` ASC),
  INDEX `accounting_verification_series` (`accounting_verification_series` ASC),
  INDEX `instruction_number` (`instruction_number` ASC),
  INDEX `accounting_date` (`accounting_date` ASC),
  INDEX `index6` (`importer` ASC),
  INDEX `fk_accounting_instruction_4_idx` (`accounting_period` ASC),
  INDEX `index8` (`accounting_period` ASC),
  CONSTRAINT `fk_accounting_instruction_1`
    FOREIGN KEY (`accounting_category`)
    REFERENCES `accounting_category` (`entity_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_instruction_2`
    FOREIGN KEY (`accounting_verification_series`)
    REFERENCES `accounting_verification_series` (`entity_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_instruction_3`
    FOREIGN KEY (`entity_id`)
    REFERENCES `entity` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_instruction_4`
    FOREIGN KEY (`accounting_period`)
    REFERENCES `accounting_period` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accounting_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounting_account` ;

CREATE TABLE IF NOT EXISTS `accounting_account` (
  `entity_id` INT(11) UNSIGNED NOT NULL,
  `account_number` INT UNSIGNED NOT NULL,
  `accounting_period` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`entity_id`),
  INDEX `fk_accounting_account_1_idx` (`accounting_period` ASC),
  CONSTRAINT `fk_accounting_account_1`
    FOREIGN KEY (`accounting_period`)
    REFERENCES `accounting_period` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_account_2`
    FOREIGN KEY (`entity_id`)
    REFERENCES `entity` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accounting_cost_center`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounting_cost_center` ;

CREATE TABLE IF NOT EXISTS `accounting_cost_center` (
  `entity_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`entity_id`),
  CONSTRAINT `fk_accounting_cost_center_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accounting_transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounting_transaction` ;

CREATE TABLE IF NOT EXISTS `accounting_transaction` (
  `entity_id` INT(11) UNSIGNED NOT NULL,
  `accounting_instruction` INT(11) UNSIGNED NOT NULL,
  `accounting_account` INT(11) UNSIGNED NOT NULL,
  `accounting_cost_center` INT(11) UNSIGNED NULL,
  `amount` INT NULL,
  `external_id` VARCHAR(45) NULL,
  PRIMARY KEY (`entity_id`),
  INDEX `fk_accounting_transactions_1_idx` (`accounting_instruction` ASC),
  INDEX `fk_accounting_transactions_2_idx` (`accounting_account` ASC),
  INDEX `fk_accounting_transactions_3_idx` (`accounting_cost_center` ASC),
  CONSTRAINT `fk_accounting_transactions_1`
    FOREIGN KEY (`accounting_instruction`)
    REFERENCES `accounting_instruction` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_transactions_2`
    FOREIGN KEY (`accounting_account`)
    REFERENCES `accounting_account` (`entity_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_transactions_3`
    FOREIGN KEY (`accounting_cost_center`)
    REFERENCES `accounting_cost_center` (`entity_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_transaction_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `entity`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `entity` (`entity_id`, `type`, `created_at`, `updated_at`, `deleted_at`, `title`, `description`) VALUES (1, 'accounting_period', NULL, NULL, NULL, 'Räkneskapsår 2013', NULL);
INSERT INTO `entity` (`entity_id`, `type`, `created_at`, `updated_at`, `deleted_at`, `title`, `description`) VALUES (2, 'accounting_period', NULL, NULL, NULL, 'Räkneskapsår 2014', NULL);
INSERT INTO `entity` (`entity_id`, `type`, `created_at`, `updated_at`, `deleted_at`, `title`, `description`) VALUES (3, 'accounting_period', NULL, NULL, NULL, 'Räkneskapsår 2015', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `accounting_period`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `accounting_period` (`entity_id`, `name`, `start`, `end`) VALUES (1, '2013', '2013-01-01', '2013-12-31');
INSERT INTO `accounting_period` (`entity_id`, `name`, `start`, `end`) VALUES (2, '2014', '2014-01-01', '2014-12-31');
INSERT INTO `accounting_period` (`entity_id`, `name`, `start`, `end`) VALUES (3, '2015', '2015-01-01', '2015-12-31');

COMMIT;

