// See ui-kit documentation for the list of all available icons
// https://getuikit.com/docs/icon
export type UiKitIconName =
    | "calendar"
    | "cart"
    | "check"
    | "chevron-down"
    | "chevron-up"
    | "cog"
    | "commenting"
    | "cloud-download"
    | "eye-slash"
    | "home"
    | "lock"
    | "plus"
    | "plus-circle"
    | "phone"
    | "mail"
    | "comment"
    | "tag"
    | "trash"
    | "refresh"
    | "search"
    | "settings"
    | "user";
